version: "2.1"
services:
  # dns:
  #   image: phensley/docker-dns
  #   hostname: dns
  #   domainname: test.lcl
  #   volumes:
  #     - ./docker.sock:/docker.sock
  php:
    image: "laig/php"
    # build: php
    networks:
      - expnet
    depends_on:
      - apache
    ports:
      # - "8080:8080"
      # - "4430:4430"
      - "9000:9000"
    volumes:
      - ./apache/apache2/:/usr/local/apache2/
      - ./public_html/:/var/www/html/
      - ./apache/logs/:/var/www/logs/
    container_name: php
    hostname: php

  apache:
    image: "laig/apache"
    restart: always
    # build: apache
    depends_on:
      - mysql
    networks:
      - expnet
    ports:
      - "8080:8080"
      - "4430:4430"
    volumes:
      - ./public_html/:/var/www/html/
    container_name: apache
    hostname: www
    domainname: test.lcl
  # mariadb:
  #   image: mariadb:10.1
  #   container_name: mariadb
  #   working_dir: /application
  #   hostname: mariadb
  #   restart: always
  #   networks:
  #     - default
  #   volumes: 
  #     - ./mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  #     - MYSQL_DATABASE=test
  #     - MYSQL_USER=root
  #   ports:
  #     - "8083:3306"
  mysql:
    image: "mysql:${MYSQL_VERSION:-latest}"
    restart: always
    networks:
      - expnet
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes: 
      - ./mysql:/var/lib/mysql
    container_name: mysql
    hostname: mysql

networks:
  expnet:
    driver: bridge