version: '3'
services:
    web:
        image: laig/nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./log/nginx:/var/log/nginx"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        networks:
            - expnet
        ports:
            - "8080:8080"
            - "4430:4430"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && cp /etc/certs/* /etc/ssl/ && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysql
    php:
        image: laig/php-fpm:${PHP_VERSION}
        restart: always
        networks:
            - expnet
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
    composer:
        image: "composer"
        networks:
            - expnet
        volumes:
            - "./web:/app"
        command: install
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        networks:
            - expnet
        ports:
            - "8081:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        volumes: 
            - ./etc/myadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        depends_on:
            - mysql
    mysql:
        image: "mysql:${MYSQL_VERSION:-latest}"
        restart: always
        networks:
            - expnet
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes: 
            - ./mysql:/var/lib/mysql
        container_name: ${MYSQL_HOST}
        hostname: ${MYSQL_HOST}
networks:
  expnet:
    driver: bridge